dist: trusty
sudo: required
language: python

addons:
  sonarqube:
    organization: "koisell-github" # the key of the org you chose at step #3

python:
  - "3.5"
  - "3.6"

# command to install dependencies
install: 
  - "pip3 install -r requirements.txt"

script:
  - sonar-scanner -X
# command to run tests
# script: pytest

notifications:
  email: false