openapi: 3.0.0
servers:
  - url: 'http://localhost:4242'
    description: On Raspberry PI
  - url: 'http://{ip}:{port}'
    variables:
      ip:
        default: 172.18.23.105
        description: Current ip of the service
      port:
        default: '4242'
        description: Current port of the service
info:
  version: 1.1.0
  title: CoffeeMachineService
paths:
  /coffee:
    get:
      description: Request a coffee
      parameters:
        - in: query
          name: volume
          description: must be between 0 and 3
          schema:
            type: integer
          required: true
        - in: query
          name: intensity
          description: must be between 0 and 4
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Your coffee is waiting you.
        '400':
          description: you have provide an invalid query.
