openapi: 3.0.0
servers:
  - url: 'http://localhost:5000'
    description: On Raspberry PI
  - url: 'http://{ip}:{port}'
    variables:
      ip:
        default: 172.18.23.105
        description: Current ip of the service
      port:
        default: '5000'
        description: Current port of the service
info:
  version: 1.1.0
  title: Gateway
components:
  schemas:
    User:
      $ref: '#/components/schemas/User'
      description: User stored in DB
      type: object
      properties:
        id:
          type: integer
          description: The user ID.
        username:
          type: string
          description: The user name.
        intensity:
          type: integer
        description: Favorite coffee intensity of the user
        volume:
          type: integer
          description: Favorite coffee volume of the user
paths:
  /coffee:
    get:
      description: Request a coffee
      responses:
        '200':
          description: Your coffee is waiting you.
        '502':
          description: Bad gateway.
        '503':
          description: Service unavailable.
        '504':
          description: Gateway timeout.
        4XX:
          description: See documentation of CoffeeMachineService
  /doc/coffee_machine:
    get:
      description: Return swagger file (yaml) of the CoffeeMachineService.
      responses:
        '200':
          description: OK.
  /users/{id}:
    get:
      description: Gets 'User' object by ID.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '502':
          description: Bad gateway.
        '503':
          description: Service unavailable.
        '504':
          description: Gateway timeout.
        4XX:
          description: See documentation of CoffeeMachineService
      parameters:
        - name: id
          in: path
          required: true
          description: ID of User to use
          schema:
            type: integer
    put:
      description: Modify An User by id
      responses:
        '200':
          description: OK
        '502':
          description: Bad gateway.
        '503':
          description: Service unavailable.
        '504':
          description: Gateway timeout.
        4XX:
          description: See documentation of CoffeeMachineService
  /doc/gateway:
    get:
      description: Return swagger file (yaml) of this Service.
      responses:
        '200':
          description: OK.
